### ISSUE TITLE
Bug with verification of users

### ISSUE THREAD

**Issue by AlexeyMishenev** [twitchbot-discord/twitchbot#1]
using command `twitch user <not twitch-verified user>` shows that this user has verification.
Not for all, seems when streamer is Affilative partner
![image](https://user-images.githubusercontent.com/22176389/48447670-92059d00-e7ad-11e8-82a1-abe05dd7afbc.png)
![image](https://user-images.githubusercontent.com/22176389/48447993-ae560980-e7ae-11e8-98c7-3c71c4b75637.png)
But 
![image](https://user-images.githubusercontent.com/22176389/48448004-b7df7180-e7ae-11e8-9f7d-9c4ed1c20ce7.png)

**Comment by devakira** [comment]
Will fix in latest patch
